# Generated by Django 5.0.4 on 2024-04-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userinfo_create_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('mobel', models.CharField(max_length=11, verbose_name='电话号码')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='价格')),
                ('level', models.SmallIntegerField(choices=[(1, '普通'), (2, '初级'), (3, '高级'), (4, '顶级')], verbose_name='级别')),
                ('status', models.SmallIntegerField(choices=[(1, '未占用'), (2, '已占用')], verbose_name='状态')),
            ],
        ),
    ]
