# Generated by Django 5.0.4 on 2024-04-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_mobel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobel',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '普通'), (2, '初级'), (3, '高级'), (4, '顶级')], default=1, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='mobel',
            name='price',
            field=models.IntegerField(verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='mobel',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '未占用'), (2, '已使用')], default=2, verbose_name='状态'),
        ),
    ]
