# Generated by Django 5.0.4 on 2024-04-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_mobel_level_alter_mobel_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobel',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '普通'), (2, '初级'), (3, '高级'), (4, '顶级')], default=1, max_length=4, verbose_name='级别'),
        ),
    ]
