# Generated by Django 5.0.4 on 2024-05-04 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_admin_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('detail', models.TimeField(verbose_name='详细信息')),
                ('level', models.SmallIntegerField(choices=[(1, '紧急'), (2, '重要'), (3, '一般')], default=1, verbose_name='级别')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.admin', verbose_name='负责人')),
            ],
        ),
    ]
